import {
  Profile,
  Project,
  Service,
  Skill,
  Experience,
  SocialLink,
  SiteSettings,
  MediaItem,
} from '../types/database';

export const initialProfile: Profile = {
  id: 'profile-anil-shrestha',
  name: 'Anil Shrestha',
  profession: 'Graphic Designer & UI/UX Specialist',
  headline: 'Creative designer turning ideas into visual experiences.',
  short_bio: 'Crafting meaningful visual identities, intuitive web & mobile interfaces, marketing collateral, and precision print solutions for clients in Pokhara, Nepal and worldwide.',
  long_bio: 'Creative designer with 3–5 years of specialized experience in visual communication, branding systems, and intuitive UI/UX design. Based in Pokhara, Nepal, I bridge human empathy with aesthetic precision across digital products, mobile interfaces, and high-impact print collateral.',
  location: 'Pokhara, Nepal',
  email: 'hello@anilshrestha.design',
  availability: 'Available for Hire & Projects',
  profile_image_url: '/src/assets/images/anil_portrait_1791182391937.jpg',
  hero_heading: 'Creative designer turning ideas into visual experiences.',
  hero_description: 'Crafting meaningful visual identities, intuitive web & mobile interfaces, marketing collateral, and precision print solutions for clients in Pokhara, Nepal and worldwide.',
  primary_cta_label: 'Explore My Work',
  primary_cta_url: '/work',
  secondary_cta_label: 'View Services',
  secondary_cta_url: '/services',
  resume_url: '/resume',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-03-01T00:00:00Z',
};

export const initialProjects: Project[] = [
  {
    id: 'proj-aura-banking',
    title: 'Aura Fintech Banking UI/UX System',
    slug: 'aura-fintech-banking-app',
    category: 'UI/UX Design',
    subcategory: 'Mobile App',
    tags: ['UI/UX Design', 'Figma', 'Design System', 'Fintech', 'Mobile App'],
    description: 'A modern, friction-free mobile banking interface with sleek dark aesthetics, intuitive transaction flows, and modular design tokens.',
    shortDescription: 'Modern mobile banking interface with sleek dark aesthetics and seamless transaction flows.',
    fullDescription: 'Aura Banking is a next-generation mobile finance platform tailored for young professionals. The design prioritizes visual clarity, instant fund transfers, interactive spending analytics, and custom card management.',
    year: '2025',
    client: 'Aura Financial Technologies',
    role: 'Lead UI/UX Designer',
    services: ['Mobile App Design', 'Design System', 'Prototyping', 'Fintech UX'],
    tools: ['Figma', 'Adobe Illustrator', 'Prototyping'],
    challenge: 'Complex financial data often overwhelms users. The challenge was simplifying multi-currency wallets and portfolio graphs without compromising detail or security.',
    solution: 'Created a sleek minimalist layout using soft ambient highlights, card elevation, high-contrast typography, and fluid touch interactions.',
    approach: 'Conducted user journey mapping for quick payments and budget alerts, followed by full Figma component library.',
    cover_image_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    ],
    project_url: 'https://figma.com/@anilshrestha',
    featured: true,
    published: true,
    sort_order: 1,
    seo_title: 'Aura Fintech Banking Mobile App — Anil Shrestha',
    seo_description: 'UI/UX case study for mobile banking by Anil Shrestha.',
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 'proj-kora-organic',
    title: 'Kora Organic Artisanal Brand & Packaging',
    slug: 'kora-organic-brand-packaging',
    category: 'Branding',
    subcategory: 'Packaging & Identity',
    tags: ['Branding', 'Visual Identity', 'Packaging', 'Typography', 'Print'],
    description: 'Complete brand identity, bespoke typography, and sustainable packaging system for a Himalayan organic botanical wellness label.',
    shortDescription: 'Himalayan organic botanical wellness brand identity and tactile packaging suite.',
    fullDescription: 'Crafted the visual identity, brand guidelines, embossed glass bottle labels, and unbleached kraft paper packaging for an ethical apothecary brand celebrating high-altitude flora.',
    year: '2025',
    client: 'Kora Botanicals Nepal',
    role: 'Brand Identity & Packaging Designer',
    services: ['Brand Strategy', 'Logo Suite', 'Custom Packaging Dielines', 'Pre-Press Oversight'],
    tools: ['Adobe Illustrator', 'Adobe Photoshop', 'Figma'],
    challenge: 'Balancing heritage Himalayan botanical cues with modern luxury retail presence for both local and export markets.',
    solution: 'Designed an elegant bilingual monogram, paired with tactile blind debossing and mineral foil accents on recyclable cotton-rag stock.',
    cover_image_url: '/src/assets/images/project_heritage_identity_1791182403227.jpg',
    gallery_urls: [
      '/src/assets/images/project_heritage_identity_1791182403227.jpg',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
    ],
    project_url: 'https://behance.net/anilshrestha',
    featured: true,
    published: true,
    sort_order: 2,
    seo_title: 'Kora Organic Brand Identity — Anil Shrestha',
    seo_description: 'Brand identity and packaging design case study by Anil Shrestha.',
    created_at: '2025-02-15T00:00:00Z',
    updated_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'proj-spectrum-poster',
    title: 'Spectrum Contemporary Music Festival Poster',
    slug: 'spectrum-music-festival-poster',
    category: 'Graphic Design',
    subcategory: 'Poster & Print',
    tags: ['Graphic Design', 'Poster Design', 'Typography', 'Print Production', 'Culture'],
    description: 'Experimental typographic exhibition poster and screenprinted promotional series for an annual Kathmandu indie sound art gathering.',
    shortDescription: 'Avant-garde risograph and silkscreen poster design with Swiss typographic grid.',
    fullDescription: 'Large-format silkscreen poster featuring kinetic sound wave deconstructions, rigorous Swiss-grid layout, and vivid metallic bronze ink overlaid on textured black archival cardstock.',
    year: '2024',
    client: 'Spectrum Arts Initiative',
    role: 'Poster Artist & Art Director',
    services: ['Poster Design', 'Screenprint Color Separation', 'Editorial Layout', 'Event Merch'],
    tools: ['Adobe InDesign', 'Adobe Illustrator', 'Adobe Photoshop'],
    challenge: 'Communicating the festival’s eclectic avant-garde line-up through a single high-impact collectible print piece.',
    solution: 'Engineered an interlocking typographic grid with layered halftones that optically vibrated under gallery spotlighting.',
    cover_image_url: '/src/assets/images/project_jazz_poster_1791182413603.jpg',
    gallery_urls: [
      '/src/assets/images/project_jazz_poster_1791182413603.jpg',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    ],
    project_url: 'https://behance.net/anilshrestha',
    featured: true,
    published: true,
    sort_order: 3,
    seo_title: 'Spectrum Music Festival Poster Design — Anil Shrestha',
    seo_description: 'Typographic silkscreen poster design by Anil Shrestha.',
    created_at: '2024-10-01T00:00:00Z',
    updated_at: '2024-10-01T00:00:00Z',
  },
  {
    id: 'proj-monograph',
    title: 'Vernacular Himalayan Architecture Monograph',
    slug: 'himalayan-architecture-monograph',
    category: 'Graphic Design',
    subcategory: 'Editorial & Book',
    tags: ['Editorial Design', 'Book Design', 'Typography', 'Print Production'],
    description: '320-page hardcover architectural monograph documenting traditional timber-and-stone settlements across western Nepal.',
    shortDescription: '320-page cloth-bound architectural monograph with custom typography and foil stamping.',
    fullDescription: 'A comprehensive editorial design project featuring custom grid layouts, bilingual Devanagari typography pairing, duotone architectural photography prepress, and bespoke silver foil cloth binding.',
    year: '2024',
    client: 'Nepal Heritage Preservation Trust',
    role: 'Editorial Book Designer',
    services: ['Book Design', 'Typographic Hierarchy', 'Image Color Grading', 'Print Specifying'],
    tools: ['Adobe InDesign', 'Adobe Photoshop'],
    challenge: 'Structuring dense architectural drawings, essays, and field photography into an inviting, collectible monograph.',
    solution: 'Built a 12-column dynamic grid with generous negative space, allowing full-bleed architectural spreads to breathe.',
    cover_image_url: '/src/assets/images/project_monograph_book_1791182423987.jpg',
    gallery_urls: [
      '/src/assets/images/project_monograph_book_1791182423987.jpg',
    ],
    project_url: 'https://dribbble.com/anilshrestha',
    featured: true,
    published: true,
    sort_order: 4,
    seo_title: 'Himalayan Architecture Monograph — Anil Shrestha',
    seo_description: 'Editorial monograph book design by Anil Shrestha.',
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2024-08-15T00:00:00Z',
  },
  {
    id: 'proj-pdf-helper',
    title: 'Pdf-helper Web Application Interface',
    slug: 'pdf-helper-interface',
    category: 'UI/UX Design',
    subcategory: 'Web Application UI',
    tags: ['UI/UX Design', 'Web Design', 'Figma', 'Design System'],
    description: 'Modern, distraction-free document reader and smart workspace interface for analyzing and organizing PDF documents.',
    shortDescription: 'Minimalist web application interface for document interaction and reading.',
    fullDescription: 'Designed the complete user experience, component design system, and responsive web interface for Pdf-helper, focusing on reading comfort and intuitive toolbars.',
    year: '2025',
    client: 'Self-Initiated / Open Source',
    role: 'Product Designer & Vibe Coder',
    services: ['UI/UX Design', 'Design System', 'Interactive Prototyping', 'Frontend Implementation'],
    tools: ['Figma', 'Tailwind CSS', 'React', 'Next.js'],
    cover_image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    ],
    project_url: 'https://github.com/anilshrestha',
    featured: false,
    published: true,
    sort_order: 5,
    seo_title: 'Pdf-helper Interface Design — Anil Shrestha',
    seo_description: 'UI/UX design case study by Anil Shrestha.',
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
  },
];

export const initialServices: Service[] = [
  {
    id: 'srv-1',
    title: 'Brand Identity & Visual Systems',
    description: 'Crafting memorable logo suites, comprehensive brand style guides, typography hierarchy, and cohesive color palettes that stand out in crowded markets.',
    icon: 'Palette',
    deliverables: [
      'Primary & Secondary Logo Suites',
      'Comprehensive Brand Guidelines (PDF)',
      'Typography & Color Palette System',
      'Stationery, Business Cards & Social Kits',
    ],
    featured: true,
    sort_order: 1,
    active: true,
  },
  {
    id: 'srv-2',
    title: 'UI/UX & Mobile / Web Interfaces',
    description: 'Designing intuitive, modern user interfaces for web and mobile applications with high-fidelity Figma prototypes and scalable component libraries.',
    icon: 'Layout',
    deliverables: [
      'Mobile & Web Application UI',
      'Interactive Figma Prototypes',
      'Design Systems & Component Specs',
      'Wireframing & Information Architecture',
    ],
    featured: true,
    sort_order: 2,
    active: true,
  },
  {
    id: 'srv-3',
    title: 'Print, Packaging & Pre-Press',
    description: 'End-to-end tactile packaging, box dielines, bottle labels, retail packaging, and print-ready production files with expert prepress color separation.',
    icon: 'Layers',
    deliverables: [
      'Custom Packaging & Label Dielines',
      'Spot UV, Foil & Emboss Separation',
      'Brochures, Catalogues & Books',
      'Vendor Print Quality Oversight',
    ],
    featured: true,
    sort_order: 3,
    active: true,
  },
  {
    id: 'srv-4',
    title: 'Graphic & Marketing Collateral',
    description: 'High-impact visual communication across event posters, social media campaign templates, large-format signage, and digital advertisements.',
    icon: 'Sparkles',
    deliverables: [
      'Cultural & Event Posters',
      'Social Media Campaign Toolkits',
      'Large Format Signage & Banners',
      'Merchandise & Apparel Graphics',
    ],
    featured: true,
    sort_order: 4,
    active: true,
  },
];

export const initialSkills: Skill[] = [
  { id: 'sk-1', name: 'Brand Identity & Strategy', category: 'Graphic Design', sort_order: 1 },
  { id: 'sk-2', name: 'UI/UX & Mobile App Design', category: 'UI/UX Design', sort_order: 2 },
  { id: 'sk-3', name: 'Figma & Design Systems', category: 'Software & Tools', sort_order: 3 },
  { id: 'sk-4', name: 'Adobe Illustrator (Vector)', category: 'Software & Tools', sort_order: 4 },
  { id: 'sk-5', name: 'Adobe Photoshop (Photo Manipulation)', category: 'Software & Tools', sort_order: 5 },
  { id: 'sk-6', name: 'Adobe InDesign (Editorial)', category: 'Software & Tools', sort_order: 6 },
  { id: 'sk-7', name: 'Packaging & Dieline Engineering', category: 'Graphic Design', sort_order: 7 },
  { id: 'sk-8', name: 'Typography & Layout', category: 'Graphic Design', sort_order: 8 },
  { id: 'sk-9', name: 'Print Pre-Press & Color Separation', category: 'Graphic Design', sort_order: 9 },
  { id: 'sk-10', name: 'Tailwind CSS & Web Vibe Coding', category: 'UI/UX Design', sort_order: 10 },
];

export const initialExperience: Experience[] = [
  {
    id: 'exp-1',
    company: 'Independent Design Studio',
    position: 'Graphic Designer & UI/UX Specialist',
    description: 'Partnering with brands, startups, and creative agencies worldwide to develop visual identities, digital interfaces, and packaging.',
    start_date: '2023',
    end_date: 'Present',
    current: true,
    location: 'Pokhara, Nepal',
    sort_order: 1,
  },
  {
    id: 'exp-2',
    company: 'Creative Studio & Agency',
    position: 'Senior Graphic Designer',
    description: 'Directed visual identity, campaign collateral, and print production across FMCG, cultural events, and retail clients.',
    start_date: '2021',
    end_date: '2023',
    current: false,
    location: 'Nepal',
    sort_order: 2,
  },
];

// Dynamic social links as explicitly requested: Facebook, Instagram, Behance, Dribbble, LinkedIn
export const initialSocialLinks: SocialLink[] = [
  { id: 'soc-fb', platform: 'Facebook', url: 'https://facebook.com', sort_order: 1, active: true },
  { id: 'soc-ig', platform: 'Instagram', url: 'https://instagram.com', sort_order: 2, active: true },
  { id: 'soc-be', platform: 'Behance', url: 'https://behance.net', sort_order: 3, active: true },
  { id: 'soc-dr', platform: 'Dribbble', url: 'https://dribbble.com', sort_order: 4, active: true },
  { id: 'soc-li', platform: 'LinkedIn', url: 'https://linkedin.com', sort_order: 5, active: true },
  { id: 'soc-gh', platform: 'GitHub', url: 'https://github.com/anilshrestha', sort_order: 6, active: true },
];

export const initialMedia: MediaItem[] = [
  {
    id: 'med-1',
    filename: 'anil_portrait.jpg',
    original_name: 'anil_portrait.jpg',
    url: '/src/assets/images/anil_portrait_1791182391937.jpg',
    file_size: 245000,
    mime_type: 'image/jpeg',
    dimensions: '1024x1024',
    alt_text: 'Portrait of Graphic Designer Anil Shrestha',
    created_at: '2026-03-01T08:00:00Z',
  },
];

export const initialSiteSettings: SiteSettings = {
  id: 'settings-1',
  site_name: 'Anil Shrestha — Graphic Designer & UI/UX Specialist',
  ga_id: '',
  google_site_verification: '',
  contact_email: 'hello@anilshrestha.design',
  allow_indexing: true,
  maintenance_mode: false,
};
